internalAuth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'internalAuth'
urlpatterns = [
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("update", views.UpdateView, name="update"),
    path("delete", views.DeleteView, name="delete"),
    path('password-reset', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html', success_url = reverse_lazy('internalAuth:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

wishManagement/urls.py
from django.urls import path, include

from . import views

app_name = "wishlist"
urlpatterns = [
    path('wishlist', views.IndexViewWishlist.as_view(), name='index'),
    path('wishlist/create', views.CreateViewWishlist, name='create'),
    path('wishlist/update/<int:pk>', views.UpdateViewWishlist, name='update'),
    path('wishlist/delete/<int:pk>', views.DeleteViewWishlist, name='delete'),

    path('wish/<int:pkWishlist>', views.IndexViewWish, name='indexWish'),
    path('wish/create/<int:pkWishlist>', views.CreateViewWish, name='createWish'),
    path('wish/update/<int:pkWish>', views.UpdateViewWish, name='updateWish'),
    path('wish/delete/<int:pkWish>', views.DeleteViewWish, name='deleteWish'),

    path('wishlist/share/<uuid:uuidWishlist>', views.ShareViewWishlist, name='share'),

    path('shared', views.IndexViewShared, name='indexShare'),
    path('shared/<int:pkWishlist>', views.DetailViewSharedWishlist, name='detailShareWishlist'),
    path('shared/wish/<int:pkWish>', views.DetailViewSharedWish, name='detailShareWish'),
    path('shared/wish/mark/<int:pkWish>', views.MarkViewSharedWish, name='markShareWish'),
    path('shared/wish/removemark/<int:pkWish>', views.UnmarkViewSharedWish, name='unmarkShareWish'),
]

wishit/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("internalAuth.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('externalAuth/', include('externalAuth.urls')),
    path('wishManagement/', include('wishManagement.urls')),
    path('priceComparison/', include('priceComparison.urls')),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/form_snippet.html
{% for field in form %}
    <div class="form-floating mb-3">
        {{ field }} {{ field.label_tag }}
    </div>
{% endfor %}

templates/home.html
{% extends "wishlist_base.html" %}

{% block title %}Wishit - Home{% endblock %}

{% block content %}

{% load static %}
    <div class="col-12 col-sm-12 col-md-6 mt-5 home bubble-bg text-center">
        <img src="{% static 'img/home/working.webp' %}" alt="WishIt" class="fadein"/>
    </div>
    <div class="col-12 col-sm-12 col-md-6 mt-5 home text-left centerHVflex flyin">
        <div>
            <h2>
                MANAGE AND SHARE YOUR WISHES
            </h2>
            <p>
                Your tool to create and manage multiple lists with unlimited wishes.            
                Share lists with friends, families and guests.
            </p>
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-6 mt-3 home text-left centerHVflex fadein">
        <div>
            <h2>
                NO ACCOUNT NECESSARY 
            </h2>
            <p>
                You can share lists with everybody. To access lists there is not even a need to create an account.
            </p>
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-6 mt-3 home bubble-bg text-center fadein">
        <img src="{% static 'img/home/people.webp' %}" alt="WishIt"/>
    </div>

    <div class="col-12 col-sm-12 col-md-6 mt-3 home bubble-bg text-center fadein">
        <img src="{% static 'img/home/event.webp' %}" alt="WishIt"/>
    </div>
    <div class="col-12 col-sm-12 col-md-6 mt-3 home text-left centerHVflex fadein">
        <div>
            <h2>
                UNLIMITED LISTS AND WISHES
            </h2>
            <p>
                Create multiple lists - for your family, for your birthday, wedding, ...
            </p>
        </div>
    </div>

{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-md px-5 py-3">
    <div class="container">    
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0 nav-fill w-100 pl-5 pr-5">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="/">HOME</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if 'wishManagement/wish' in request.path %} active {% endif %}" href="{% url 'wishlist:index' %}">PERSONAL</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if 'wishManagement/share' in request.path %} active {% endif %}" href="{% url 'wishlist:indexShare' %}">SHARED</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
              </a>
              <ul class="dropdown-menu {% if 'accounts' in request.path %} active {% endif %}" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                <li><a class="dropdown-item" href="{%url 'internalAuth:update' %}">Manage Profile</a></li>
              </ul>
            </li>
          {% endif %}
        </ul>
        
        {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url 'login' %}">
              <button class="btn btn-outline-success" type="button">Log In</button>
            </a>
            <a class="nav-link" href="{% url 'internalAuth:signup' %}">
              <button class="btn btn-outline-success" type="button">Sign Up</button>
            </a>     
        {% endif %}
      </div>
    </div>
  </nav>

templates/wishlist_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Wishit{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    </head>
    <body>

        <div class="bg-layer h-100">

            {% include 'nav.html' %}

            {% if messages %}
            <div class="container messages my-5">
                {% for message in messages %}
                <div class="alert alert-{{message.level_tag}}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            </div>            
            {% endif %}


            <div class="container mt-5" id="page">
                <div class="row justify-content-center">
                    {% block content %}

                    {% endblock %}         
                </div>
            </div>
        </div>

        <script src="/static/js/bootstrap.bundle.min.js"></script>
        <script src="/static/js/jquery.min.js"></script>
        <script src="/static/js/custom.js"></script>
    </body>
</html>