internalAuth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'internalAuth'
urlpatterns = [
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("update", views.UpdateView, name="update"),
    path("delete", views.DeleteView, name="delete"),
    path('password-reset', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html', success_url = reverse_lazy('internalAuth:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

wishit/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("internalAuth.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('externalAuth/', include('externalAuth.urls')),
    path('wishManagement/', include('wishManagement.urls')),
    path('priceComparison/', include('priceComparison.urls')),
]

internalAuth/models.py
from django.contrib.auth.models import AbstractUser

class WishitUser(AbstractUser):
    def __str__(self):
        return self.username

internalAuth/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import WishitUser

class WishitUserCreationForm(UserCreationForm):
    class Meta:
        model = WishitUser
        fields = ("username", "email")
    template_name = "form_snippet.html"
    def __init__(self, *args, **kwargs):
        super(WishitUserCreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'hopefully not visible'

class WishitUserChangeForm(UserChangeForm):
    class Meta:
        model = WishitUser
        fields = ("username", "email")

class WishitUserUpdateForm(UserChangeForm):
    class Meta:
        model = WishitUser
        fields = ("username", "email")
    template_name = "form_snippet.html"
    def __init__(self, *args, **kwargs):
        super(WishitUserUpdateForm, self).__init__(*args, **kwargs)
        del self.fields['password']
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'hopefully not visible'

class WishitUserForm(ModelForm):
    class Meta:
        model=WishitUser
        fields=('username','email')
    template_name = "form_snippet.html"
    def __init__(self, *args, **kwargs):
        super(WishitUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'hopefully not visible'

internalAuth/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth import logout
from .forms import WishitUserCreationForm, WishitUserUpdateForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import WishitUser
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

class SignUpView(CreateView):
    form_class = WishitUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

def UpdateView(request):
    if request.method == 'POST':
        form = WishitUserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('internalAuth:update'))
    else:
        form = WishitUserUpdateForm(instance=request.user)
    return render(request, 'profile/update.html', {'form': form})

def DeleteView(request):
    user = get_object_or_404(WishitUser, pk=request.user.pk)
    user.delete()
    logout(request)
    return HttpResponseRedirect('/')

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'password_reset/password_reset.html'
    email_template_name = 'password_reset/password_reset_email.html'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('home')


# Helper Function
def send_400():
    response = HttpResponse()
    response.status_code = 400              
    return response

internalAuth/templates/password_reset/password_reset.html
{% extends "wishlist_base.html" %}
{% block content %}
<div class="col-12 col-sm-12 col-md-8 col-lg-4">
    <h2>Reset password</h2>

    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        
        <div class="form-floating mb-3">
          <input class="form-control" type="email" name="email" id="id_email" required/>
          <label for="id_email">Email</label>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>

    <div class="wishit_link text-center p-1">
        <a href="{% url 'internalAuth:signup' %}">Create A New Account</a>
    </div>
    <div class="wishit_link text-center p-1">
        <a href="{% url 'login' %}">Back To Login</a>
    </div>
</div>
{% endblock content %}

internalAuth/templates/password_reset/password_reset_complete.html
{% extends "wishlist_base.html" %}
{% block content %}
    <div class="col-12 col-sm-12 col-md-8 col-lg-4">
        <h2>Reset password</h2>
        <p>
            Your password has been set. <br/>
            You may go ahead and <a class="wishit_link" href="{% url 'login' %}">Login Here</a>
        </p>
    </div>
{% endblock content %}

internalAuth/templates/password_reset/password_reset_confirm.html
{% extends "wishlist_base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}

    <div class="col-12 col-sm-12 col-md-8 col-lg-4">
        <h2>Reset password</h2>

                    {% if validlink %}
                            <form method="POST">                                   
                                {% csrf_token %}
                                {% if form.errors %}
                                    {% csrf_token %}
                                    {% for key, value in form.errors.items %}
                                        {{ value }}
                                    {% endfor %} 
                                {% endif %}

                                <div class="form-floating mb-3">
                                    <input type="password" name="new_password1" autocomplete="new-password"
                                            class="form-control" required id="id_new_password1"
                                            placeholder="Enter password"/>
                                    <label class="small mb-1" for="id_new_password1">New Password</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="password" name="new_password2" autocomplete="new-password"
                                            required id="id_new_password2" class="form-control"
                                            placeholder="Confirm password"/>
                                    <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                </div>
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </form>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}

    </div>

{% endblock content %}

internalAuth/templates/password_reset/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'internalAuth:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}