wishManagement/urls.py
from django.urls import path, include

from . import views

app_name = "wishlist"
urlpatterns = [
    path('wishlist', views.IndexViewWishlist.as_view(), name='index'),
    path('wishlist/create', views.CreateViewWishlist, name='create'),
    path('wishlist/update/<int:pk>', views.UpdateViewWishlist, name='update'),
    path('wishlist/delete/<int:pk>', views.DeleteViewWishlist, name='delete'),

    path('wish/<int:pkWishlist>', views.IndexViewWish, name='indexWish'),
    path('wish/create/<int:pkWishlist>', views.CreateViewWish, name='createWish'),
    path('wish/update/<int:pkWish>', views.UpdateViewWish, name='updateWish'),
    path('wish/delete/<int:pkWish>', views.DeleteViewWish, name='deleteWish'),

    path('wishlist/share/<uuid:uuidWishlist>', views.ShareViewWishlist, name='share'),

    path('shared', views.IndexViewShared, name='indexShare'),
    path('shared/<int:pkWishlist>', views.DetailViewSharedWishlist, name='detailShareWishlist'),
    path('shared/wish/<int:pkWish>', views.DetailViewSharedWish, name='detailShareWish'),
    path('shared/wish/mark/<int:pkWish>', views.MarkViewSharedWish, name='markShareWish'),
    path('shared/wish/removemark/<int:pkWish>', views.UnmarkViewSharedWish, name='unmarkShareWish'),
]

wishit/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("internalAuth.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('externalAuth/', include('externalAuth.urls')),
    path('wishManagement/', include('wishManagement.urls')),
    path('priceComparison/', include('priceComparison.urls')),
]

wishManagement/models.py
from django.db import models
import uuid
from internalAuth.models import WishitUser

# Create your models here.
class Wishlist(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(default=None, blank=True, null=True)
    owner = models.ForeignKey(WishitUser, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    def viewers(self):
        return userConnectWishlist.objects.filter(wishlist_id=self.pk).exists()

class Wish(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(default=None, blank=True, null=True)
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    product = models.CharField(max_length=100, default=None, blank=True, null=True)
    count = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    def marked(self):
        return WishMarks.objects.filter(wish_id=self.pk).exists()

class userConnectWishlist(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField(default=None, blank=True, null=True)
    user_id = models.ForeignKey(WishitUser, on_delete=models.CASCADE)
    wishlist_id = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class WishMarks(models.Model):
    wish_id = models.ForeignKey(Wish, on_delete=models.CASCADE)
    user_id = models.ForeignKey(WishitUser, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.wish_id

wishManagement/forms.py
from django.forms import ModelForm
from .models import Wishlist, Wish

class WishlistForm(ModelForm):
    class Meta:
        model=Wishlist
        fields=('title','description')
    template_name = "form_snippet.html"
    def __init__(self, *args, **kwargs):
        super(WishlistForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'hopefully not visible'

class WishForm(ModelForm):
    class Meta:
        model=Wish
        fields=('title','description', 'product', 'count')
    template_name = "form_snippet.html"
    def __init__(self, *args, **kwargs):
        super(WishForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = 'hopefully not visible'

wishManagement/views.py
from .models import Wishlist, Wish, userConnectWishlist, WishMarks
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import WishForm, WishlistForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

# Wishlist
class IndexViewWishlist(LoginRequiredMixin, generic.ListView):
    template_name = 'wishlist/index.html'
    context_object_name = 'wishlists'

    def get_queryset(self):
        """Return all wishlists."""
        return Wishlist.objects.filter(owner=self.request.user.id)

def CreateViewWishlist(request):
    if request.method == 'POST':
        form = WishlistForm(request.POST)
        if form.is_valid():                       
            wishlist = Wishlist(title = form.cleaned_data['title'], description = form.cleaned_data['description'], owner = request.user)
            wishlist.save()
            return HttpResponseRedirect(reverse('wishlist:indexWish', args=[wishlist.pk]))
    else:
        form = WishlistForm()
    return render(request, 'wishlist/create.html', {'form': form})

def UpdateViewWishlist(request, pk):
    wishlist = get_object_or_404(Wishlist, pk=pk)
    if wishlist.owner != request.user:
        send_400()
    if request.method == 'POST':
        form = WishlistForm(request.POST)
        if form.is_valid():                       
            wishlist.title = form.cleaned_data['title']
            wishlist.description = form.cleaned_data['description']
            wishlist.save()
            return HttpResponseRedirect(reverse('wishlist:indexWish', args=[wishlist.pk]))
    else:        
        form = WishlistForm(instance=wishlist)
    return render(request, 'wishlist/update.html', {'form': form, 'wishlist': wishlist})

def DeleteViewWishlist(request, pk):
    wishlist = get_object_or_404(Wishlist, pk=pk)
    if wishlist.owner == request.user:
        wishlist.delete()
        return HttpResponseRedirect(reverse('wishlist:index'))          
    return send_400()

# Wish
def IndexViewWish(request, pkWishlist):
    wishlist = get_object_or_404(Wishlist, pk=pkWishlist)
    if wishlist.owner != request.user:
        return send_400()
    wishes = Wish.objects.filter(wishlist=wishlist.id)
    return render(request, 'wish/index.html', {'wishlist': wishlist, 'wishes': wishes})

def CreateViewWish(request, pkWishlist):
    wishlist = get_object_or_404(Wishlist, pk=pkWishlist)
    if wishlist.owner != request.user:
        return send_400() 
    if request.method == 'POST':
        form = WishForm(request.POST)
        if form.is_valid():                   
            wish = Wish(title = form.cleaned_data['title'], description = form.cleaned_data['description'], wishlist = wishlist, product = form.cleaned_data['product'], count = form.cleaned_data['count'])
            wish.save()
            return HttpResponseRedirect(reverse('wishlist:indexWish', args=[wishlist.pk]))
    else:
        form = WishForm()
    return render(request, 'wish/create.html', {'form': form, 'wishlist': wishlist})

def UpdateViewWish(request, pkWish):
    wish = get_object_or_404(Wish, pk=pkWish)
    if wish.wishlist.owner != request.user:
        return send_400()    
    if request.method == 'POST':
        form = WishForm(request.POST)
        if form.is_valid():               
            wish.title = form.cleaned_data['title']
            wish.description = form.cleaned_data['description']
            wish.product = form.cleaned_data['product']
            wish.count = form.cleaned_data['count']
            wish.save()
            return HttpResponseRedirect(reverse('wishlist:indexWish', args=[wish.wishlist.pk]))
    else:
        form = WishForm(instance=wish)
    return render(request, 'wish/update.html', {'form': form, 'wish': wish, 'wishlist': wish.wishlist})

def DeleteViewWish(request, pkWish):
    wish = get_object_or_404(Wish, pk=pkWish)
    if wish.wishlist.owner == request.user:
        wish.delete()
        return HttpResponseRedirect(reverse('wishlist:indexWish', args=[wish.wishlist.pk]))          
    return send_400()

# Share
def ShareViewWishlist(request, uuidWishlist):
    wishlist = get_object_or_404(Wishlist, uuid = uuidWishlist)
    if wishlist.owner != request.user:
        if not userConnectWishlist.objects.filter(user_id = request.user, wishlist_id = wishlist).exists():
            userConnectVar = userConnectWishlist(user_id = request.user, wishlist_id = wishlist)
            userConnectVar.save()
    return HttpResponseRedirect(reverse('wishlist:detailShareWishlist', args=[wishlist.pk])) 

def IndexViewShared(request):
    shared_list = userConnectWishlist.objects.values_list('wishlist_id', flat=True).filter(user_id = request.user)
    wishlists = Wishlist.objects.filter(pk__in=shared_list)
    marked_list = WishMarks.objects.values_list('wish_id', flat=True).filter(user_id = request.user)
    wishes = Wish.objects.filter(pk__in=marked_list)
    return render(request, 'shared/index.html', {'wishlists': wishlists, 'wishes': wishes})

def DetailViewSharedWishlist(request, pkWishlist):
    wishlist = get_object_or_404(Wishlist, pk=pkWishlist)
    if not userConnectWishlist.objects.filter(user_id = request.user, wishlist_id = pkWishlist).exists():
        send_400(403)
    wishes = Wish.objects.filter(wishlist=wishlist.id)
    return render(request, 'shared/detailWishlist.html', {'wishlist': wishlist, 'wishes': wishes})
    
def DetailViewSharedWish(request, pkWish):
    wish = get_object_or_404(Wish, pk=pkWish)
    if not userConnectWishlist.objects.filter(user_id = request.user, wishlist_id = wish.wishlist.pk).exists():
        send_400(403)    
    return render(request, 'shared/detailWish.html', {'wish': wish, 'wishlist': wish.wishlist})

def MarkViewSharedWish(request, pkWish):
    wish = get_object_or_404(Wish, pk=pkWish)
    if not userConnectWishlist.objects.filter(user_id = request.user, wishlist_id = wish.wishlist.pk).exists():
        send_400(403)   
    mark = WishMarks(user_id = request.user, wish_id = wish)
    mark.save()
    return HttpResponseRedirect(reverse('wishlist:detailShareWishlist', args=[wish.wishlist.pk]))

def UnmarkViewSharedWish(request, pkWish):
    wish = get_object_or_404(Wish, pk=pkWish)
    mark = get_object_or_404(WishMarks, wish_id = wish.pk)
    # actor can be owner or marker of list
    if not (request.user == mark.user_id or request.user == wish.wishlist.owner):
        send_400(403)   
    mark.delete()
    return render(request, 'shared/detailWish.html', {'wish': wish, 'wishlist': wish.wishlist})

# Helper Function
def send_400(code = 400):
    response = HttpResponse()
    response.status_code = code              
    return response

wishManagement/templates/wish/create.html
{% extends 'wishlist_base.html' %}

{% block content %}

{% include 'wish/snippets/wishlist.html' with wishlist=wishlist %}

    <div class="col-12 col-sm-12 col-md-12 col-lg-8">
        <h2>Add a new wish</h2>
        <div class="rounded content-box m-1 p-5"> 
            <form action="{% url 'wishlist:createWish' wishlist.id %}" method="post">                
                {% csrf_token %}
                    {{ form }}
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
    <datalist id="products">
    </datalist>

{% endblock %}

wishManagement/templates/wish/index.html
{% extends 'wishlist_base.html' %}

{% block content %}

{% include 'wish/snippets/wishlist.html' with wishlist=wishlist %}

    {% if wishes %}

        <div class="index col-12 col-sm-12 col-md-6 col-lg-4">
            <a href="{% url 'wishlist:createWish' wishlist.id %}">
                <div class="rounded text-center content-box add m-1 p-5">
                    <h3>Add another wish</h3>
                    <span class="mt-2 details-button">Get started</span>
                </div>
            </a>
        </div>

        {% for wish in wishes %}
            <div class="index col-12 col-sm-12 col-md-6 col-lg-4">
                <a href="{% url 'wishlist:updateWish' wish.id %}">
                    <div class="rounded text-center content-box m-1 p-5">
                        <h3>{{ wish.title }}</h3>
                        <span class="mt-2 details-button">Details</span>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% else %}        
        <div class="index col-12 col-sm-12 col-md-6 col-lg-4">
            <a href="{% url 'wishlist:createWish' wishlist.id %}">
                <div class="rounded text-center content-box m-1 p-5">
                    <h3>No wishes yet.</h3>
                    <span class="mt-2 details-button">Get started</span>
                </div>
            </a>
        </div>
    {% endif %}
    
{% endblock %}

wishManagement/templates/wish/update.html
{% extends 'wishlist_base.html' %}

{% block content %}

{% include 'wish/snippets/wishlist.html' with wishlist=wishlist %}

    <div class="col-12 text-center">
        <h2>Update an existing wish</h2>
    </div>

    <div class="col-12 col-sm-12 col-md-9 col-lg-6 col-xl-6">
        <div class="rounded content-box m-1 p-5">  
            {% if wishlist.viewers %}
                <small class="d-block p-1 text-center">List is shared with other users!</small>
            {% endif %}
            <form action="{% url 'wishlist:updateWish' wish.id %}" method="post">
                {% csrf_token %}
                {{ form }}

                {% include 'timestamps.html' with created=wishlist.created updated=wishlist.updated %}

                <input class="btn btn-primary mt-3" type="submit" value="Submit">
            </form>
            <div class="delete-box">
                <a href="{% url 'wishlist:deleteWish' wish.id %}">
                    <button class="btn btn-delete">
                        DELETE
                    </button>
                </a>
            </div>
        </div>
    </div>
    {% if not wish.product == None %}
        <div class="col-12 col-sm-12 col-md-3 col-lg-4 col-xl-3 rounded p-5 m-2" id="offers" data-url="{{ wish.product }}">        
            <p>
                <strong>Best offers:</strong><br>
                Buy <span class="title"></span> for 
                <ul>

                </ul>
            </p>
        </div>
    {% endif %}
    <datalist id="products">
    </datalist>
    
{% endblock %}